//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarHistory
    {
        public int Id { get; set; }
        public int LastOwnerId { get; set; }
        public string VIN { get; set; }
        public System.DateTime OwnerFrom { get; set; }
        public System.DateTime OwnerTo { get; set; }
        public Nullable<bool> IsSold { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> sPrice { get; set; }
        public string LastLicencePlate { get; set; }
        public Nullable<int> LastOdometer { get; set; }
    
        public virtual VIN VIN1 { get; set; }
    }
}
