//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.ServiceHistory = new HashSet<ServiceHistory>();
        }
    
        public long Id { get; set; }
        public string VIN { get; set; }
        public string LicencePlate { get; set; }
        public string Color { get; set; }
        public int StartOdometer { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> FirstRegistration { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<decimal> PowerKM { get; set; }
        public Nullable<decimal> PowerKW { get; set; }
        public Nullable<int> SeatsNo { get; set; }
        public Nullable<short> CarTypeId { get; set; }
    
        public virtual Brands Brands { get; set; }
        public virtual CarType CarType { get; set; }
        public virtual Colours Colours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceHistory> ServiceHistory { get; set; }
    }
}
