//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceHistoryService
    {
        public int Id { get; set; }
        public short ServiceDictionaryId { get; set; }
        public int ServieHistoryId { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
    
        public virtual ServiceDictionary ServiceDictionary { get; set; }
        public virtual ServiceHistory ServiceHistory { get; set; }
    }
}
