//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceStations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceStations()
        {
            this.ServiceHistory = new HashSet<ServiceHistory>();
        }
    
        public int Id { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string BuildingNo { get; set; }
        public string ServiceName { get; set; }
        public Nullable<System.DateTime> insDate { get; set; }
        public int RegistrationId { get; set; }
        public string RegistrationNo { get; set; }
        public string PhoneNo { get; set; }
        public string MobilePhoneNo { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual RegistrationDictionary RegistrationDictionary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceHistory> ServiceHistory { get; set; }
    }
}
